name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12785
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#1c1c1c'
    - '#c2c2c2'
    - '#7b7b7b'
    - '#a3a3a3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
