name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0.77322
typography_spectrum: 0.35874
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe6e3'
    - '#1e3137'
    - '#3e4847'
    - '#76786b'
    - '#bdb2a0'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
