name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0.5386796125676483
typography_spectrum: 0.2395428738091141
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.918642591452226
  lightness: 0.14756338205188513
  saturation: 0.6241423094179481
  rhythmicContrast: 0.10898332367651165
purpose: []
