name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0.25838
typography_spectrum: 0.44468
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000d00'
    - '#885c39'
    - '#007889'
    - '#89af00'
  brandStrength: 0.918642591452226
  lightness: 0.14756338205188513
  saturation: 0.6241423094179481
  rhythmicContrast: 0.10898332367651165
purpose: []
