name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0.21297
typography_spectrum: 0.15189
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#f5f5f5'
    - '#b4b4b4'
    - '#4e4e4e'
    - '#7c7c7c'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
