name: Ahorrando Entre Todos
favicon: null
layout_spectrum: 0.25838
typography_spectrum: 0.44468
title: Ahorrando entre todos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2c2c'
    - '#909090'
    - '#c98427'
    - '#ff6c63'
  brandStrength: 0.918642591452226
  lightness: 0.14756338205188513
  saturation: 0.6241423094179481
  rhythmicContrast: 0.10898332367651165
purpose: []
